system = "slurm"

[head]
listen = "edge:///work2/USER/grain-edge-sp2" # FIXME: fill in username

[worker]
log_file = "./w{{HHMMSS}}-sp2.log"
dial = "edge:///work2/USER/grain-edge-sp2" # FIXME: fill in username

[script]
queue = "skx-dev"
#queue = "skx-normal"
walltime = "00:30:00"
cores = 48
memory = 150

setup_cleanup = '''
# load modules, source profiles, make cache dir, etc.
'''

# We need a custom template as sp2 rejects submission with `--mem` set
[custom_system]
submit_cmd = "sbatch"
directory = "#SBATCH"
template = """{c.script.shebang}
#SBATCH -J {c.name}
#SBATCH -p {c.script.queue}
#SBATCH --nodes=1
#SBATCH --ntasks-per-node={c.script.cores}
#SBATCH --time={c.script.walltime}
#SBATCH -o {c.log_file}
{c.script.extra_args_str}

{{MAIN}}
"""
