system = "slurm"

[head]
listen = "edge:///N/slate/USER/grain-edge-br3" # FIXME: fill in username

[worker]
log_file = "./w{{HHMMSS}}-br.log"
dial = "edge:///N/slate/USER/grain-edge-br3" # FIXME: fill in username

[script]
queue = "debug"
#queue = "general"
walltime = "4:00:00"
cores = 48
memory = 58

setup_cleanup = '''
# load modules, source profiles, make cache dir, etc.
'''
