system = "slurm"

[head]
listen = "tcp://:4242"
#listen = "bridge://x@x.x.x.x:x"
cmd = '''
python YOUR_ENTRYPOINT.py
'''

[head.script]
queue = "general"
walltime = "168:00:00"

[worker]
log_file = "./w{{HHMMSS}}-qz.log"
dial = "tcp://h1.quartz.uits.iu.edu:4242" # h1 or h2
#dial = "bridge://x@x.x.x.x:x"
cli_dial = "tcp://h1.quartz.local:4242" # h1 or h2

[script]
queue = "debug"
#queue = "general"
walltime = "48:00:00"
cores = 128
memory = 502

setup_cleanup = '''
# load modules, source profiles, make cache dir, etc.
'''

