system = "slurm"

address = "edge:///N/slate/USER/grain-edge-cb" # FIXME: fill in username

[worker]
log_file = "./w{{HHMMSS}}-cb.log"

[script]
queue = "debug"
#queue = "general"
walltime = "1:00:00"
cores = 24
memory = 250

setup_cleanup = '''
# load modules, source profiles, make cache dir, etc.
'''

