# An example grain config file for generating worker
# scripts. Entry marked as optional is showing its
# default value. Strings like {{HHMMSS}} are
# template-variable provided.
# (e.g. `{{HHMMSS}}` will be replaced by hhmmss
# representation of submission time). They are
# evaluated during submission.
# Try running `grain up -c THIS_FILE --dry` to see
# the job script generated.

[head]
addr = "elogin1.bigred3.uits.iu.edu"

[worker]
system = "slurm"
log_dir = "/PATH/TO/GRAIN_WORKER/LOG_DIR"
name = "w{{HHMMSS}}" # optional
log_filename = "w{{HHMMSS}}.log" # optional

[worker.script]
shebang = "#!/bin/bash" # optional
queue = "general"
walltime = "12:00:00" # optional
PPN = 48
MPN = 60
extra_args = [] # optional

# `defer` is a magic statement that makes the cmd
# in its line to be executed during clean up.
# All the other lines are setup commands to be
# executed before launching the worker process.
setup_cleanup = '''
module load /N/soft/cle6/modules/APPLICATIONS/gaussian/16

export GAUSS_SCRDIR="/PATH/TO/GAUSCRDIR/$(hostname)"
mkdir -p $GAUSS_SCRDIR
defer rm -r $GAUSS_SCRDIR

source ~/.zprofile
'''
