system = "slurm"

address = "edge:///N/slate/USER/grain-edge-qz" # FIXME: fill in username

[worker]
log_file = "./w{{HHMMSS}}-qz.log"

[script]
queue = "debug"
#queue = "general"
walltime = "48:00:00"
cores = 128
memory = 502

setup_cleanup = '''
# load modules, source profiles, make cache dir, etc.
'''

