# https://docs.readthedocs.io/en/latest/config-file/index.html
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3"

sphinx:
   configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt
